### ISSUE TITLE
Global variable undefined when testing with Jest

### ISSUE THREAD

**Issue by gchenglevi** [arthanzel/node-config-webpack#3]
This runs fine and my global config variable is defined when running outside of a test environment.

However, when I run this with vue-cli and jest unit testing (e.g. `vue-cli-service test:unit`), I get a

```
  ● Test suite failed to run

    ReferenceError: APP_CONFIG is not defined
```
```
// vue.config.js
...
 configureWebpack: {
    plugins: [
      new ConfigWebpackPlugin('APP_CONFIG')
    ]
  },
...
```

What is a good way around this? Is it because Jest starts executing the JS files before the `node-config` can finish switching out all global variables with their values?

**Comment by arthanzel** [comment]
I presume it's because Jest doesn't involve webpack when running tests. Webpack is the one that's injecting the config object into the code. To make it work in Jest, you'll have to configure a [global](https://jestjs.io/docs/en/configuration#globals-object) with your config.

A known issue with Jest is that there's a lot of duplication between the Jest and Webpack configs.

**Comment by gchenglevi** [comment]
Thanks, I tried setting globals in the Jest config but problem was the config was supposed to be dynamic (taking from test.json first, and then the rest from default.json). However, I suppose I can provide a complete copy of the test config. However, I think I may end up using option 1 here: github.com/lorenwest/node-config/wiki/Webpack-Usage

**Comment by arthanzel** [comment]
You would need to put the config object itself as a Jest global. `node-config-webpack` shouldn't play a role here. There's no reason it shouldn't pull from `test.json` if the environment is set correctly. Can you link a repo where you see this problem?
